import Head from 'next/head';
import React from 'react';

import { Inter } from 'next/font/google';
import { HomePage } from '../src/components/home/home';

const inter = Inter({ subsets: ['latin'] });

interface Props {
  data: any;
}

const Home: React.FC<Props> = ({ data }) => {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </div>
  );
};

// Use to fetch data from data folder.
export async function getServerSideProps() {
  const { events_categories } = await import('../data/data.json');

  return {
    props: {
      data: JSON.parse(JSON.stringify(events_categories)),
    },
  };
}

export default Home;
